variables:
  MAIN__PROJECT: "root/gitlab_pipeline_templates"
  SEND_MAIL__HOST: "smtp.goneo.de"
  #SEND_MAIL__PORT: "587" # if not defined, then use 587
  SEND_MAIL__FROM: "no-reply@hl-dev.de"
  # SEND_MAIL__USER: "no-reply@hl-dev.de" # if not defined, then use SEND_MAIL__FROM
  # SEND_MAIL__TO defined in ci variables
  # SEND_MAIL__PASSWORD defined in ci variables for security reasons
  SEND_MAIL__SUBJECT: "Test Mail"
  SEND_MAIL__MESSAGE: "hello world"

include:
  - project: "root/gitlab_pipeline_templates"
    file: general/Send_Mail.yml
