stages:
  - Send_Mail

Send_Mail:
  stage: Send_Mail
  image: alpine
  before_script:
    - apk add msmtp --no-cache
    - apk add mailx --no-cache
    - msmtp --version
    # - mail --version #commented because can't get version
  script:
    - |
      echo -e "# Set default values for all following accounts.
      defaults
      auth           on
      tls            on
      tls_trust_file /etc/ssl/certs/ca-certificates.crt
      syslog         off

      # MyMail
      account        MyMail
      host           $SEND_MAIL__HOST
      port           ${SEND_MAIL__PORT-587}
      from           $SEND_MAIL__FROM
      user           ${SEND_MAIL__USER-$SEND_MAIL__FROM}
      password       $SEND_MAIL__PASSWORD

      # Set a default account
      account default : MyMail
      aliases        /etc/aliases" > /etc/msmtprc

    - ln -sf /usr/bin/msmtp /usr/bin/sendmail
    - ln -sf /usr/bin/msmtp /usr/sbin/sendmail

    - |
      echo -e "root: $SEND_MAIL__TO
      default: $SEND_MAIL__TO" > /etc/aliases
    - echo $SEND_MAIL__MESSAGE | mail -s "$SEND_MAIL__SUBJECT" "$SEND_MAIL__TO"
    - |
      cat <<'EOF'
                 __,__
        .--.  .-"     "-.  .--.
      / .. \/  .-. .-.  \/ .. \
      | |  '|  /   Y   \  |'  | |
      | \   \  \ 0 | 0 /  /   / |
      \ '- ,\.-"""""""-./, -' /
        `'-' /_   ^ ^   _\ '-'`
            |  \._   _./  |
            \   \ `~` /   /
            '._ '-=-' _.'
               '~---~'
        |------------------|
        | devcodemonkey.de |
        |------------------|
      EOF
