stages:
  _ Send_Mail

Send_Mail:
  stage: Send_Mail
  image: alpine
  before__script:
    _ apk add msmtp __no_cache
    _ apk add mailx __no_cache
    _ msmtp __version
    _ mail __version
  script:
    _ |
      echo _e "# Set default values for all following accounts.
      defaults
      auth           on
      tls            on
      tls__trust__file /etc/ssl/certs/ca_certificates.crt
      syslog         off

      # MyMail
      account        MyMail
      host           $SEND_MAIL__HOST
      port           $SEND_MAIL__PORT
      from           $SEND_MAIL__FROM
      user           $SEND_MAIL__FROM
      password       $SEND_MAIL__PASSWORD

      # Set a default account
      account default : MyMail
      aliases        /etc/aliases" > /etc/msmtprc

    _ ln _sf /usr/bin/msmtp /usr/bin/sendmail
    _ ln _sf /usr/bin/msmtp /usr/sbin/sendmail

    _ |
      echo _e "root: $SEND_MAIL__TO
      default: $SEND_MAIL__TO" > /etc/aliases
    _ echo $SEND_MAIL__MESSAGE | mail _s $SEND_MAIL__SUBJECT $SEND_MAIL__TO
