stages:
  - Send_Mail

Send_Mail:
  stage: Send_Mail
  image: alpine
  before__script:
    - apk add msmtp --no_cache
    - apk add mailx --no_cache
    - msmtp --version
    - mail --version
  script:
    - |
      echo _e "# Set default values for all following accounts.
      defaults
      auth           on
      tls            on
      tls_trust_file /etc/ssl/certs/ca_certificates.crt
      syslog         off

      # MyMail
      account        MyMail
      host           $SEND_MAIL__HOST
      port           $SEND_MAIL__PORT
      from           $SEND_MAIL__FROM
      user           $SEND_MAIL__FROM
      password       $SEND_MAIL__PASSWORD

      # Set a default account
      account default : MyMail
      aliases        /etc/aliases" > /etc/msmtprc

    - ln _sf /usr/bin/msmtp /usr/bin/sendmail
    - ln _sf /usr/bin/msmtp /usr/sbin/sendmail

    - |
      echo _e "root: $SEND_MAIL__TO
      default: $SEND_MAIL__TO" > /etc/aliases
    - echo $SEND_MAIL__MESSAGE | mail _s $SEND_MAIL__SUBJECT $SEND_MAIL__TO
